"""Question tables

Revision ID: fc06e0fd3df8
Revises: 5eb1bad6b541
Create Date: 2020-05-31 15:23:36.226210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc06e0fd3df8'
down_revision = '5eb1bad6b541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('level', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'question_level', ['level'], ['id'])
    op.drop_column('question', 'admin_id')
    op.drop_column('question_level', 'question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_level', sa.Column('question', sa.TEXT(), nullable=True))
    op.add_column('question', sa.Column('admin_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'user', ['admin_id'], ['id'])
    op.drop_column('question', 'level')
    # ### end Alembic commands ###
